export class CreatureFilter {
    alignment: number[]
    type: number[]
    size: number[]
    armorTag: number[]
    speeds_MSR: number[]
    immunities_MSR: number[]
    resists_MSR: number[]
    vulnerabilities_MSR: number[]
    feelings_MSR: number[]
    savingThrows_MSR: number[]
    skills_MSR: number[]
    conditionsImmunities_MSR: number[]
    languages_MSR: number[]
    regions_MSR: number[]
}